# Generated by Django 4.2 on 2024-06-23 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_image', models.ImageField(blank=True, max_length=250, null=True, upload_to='technology/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_technology', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
