# Generated by Django 4.2 on 2024-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_technologyused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyused',
            name='technology_image',
        ),
        migrations.AddField(
            model_name='technologyused',
            name='technology_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
