# Generated by Django 4.2 on 2024-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_address_user_phone_number_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
