# Generated by Django 4.2 on 2024-02-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
