services:
  - type: web
    plan: free
    name: portfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn portfolio_api.asgi:application -k uvicorn.workers.UvicornWorker"
