# Generated by Django 4.2 on 2024-06-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_github_link_project_preview_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_technology', to='api.technologyused'),
        ),
    ]
