# Generated by Django 4.2 on 2024-06-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(null=True, related_name='project_technology', to='api.technologyused'),
        ),
    ]
