# Generated by Django 4.2 on 2024-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_project_technology_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
